/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "fragment BlogPublicFragment on BlogPublic {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n}\n\nfragment BlogFragment on Blog {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n  content\n}\n\nquery GetBlogs($page: Int, $limit: Int, $filter: BlogFilter) {\n  getBlogs(page: $page, limit: $limit, filter: $filter) {\n    success\n    message\n    data {\n      docs {\n        ...BlogPublicFragment\n      }\n      totalDocs\n      limit\n      totalPages\n      page\n      pagingCounter\n      hasPrevPage\n      hasNextPage\n      prevPage\n      nextPage\n    }\n  }\n}\n\nquery GetBlog($slug: String!) {\n  getBlog(slug: $slug) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nquery GetBlogById($id: ID!) {\n  getBlogById(id: $id) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nmutation DeleteBlog($blogId: ID!) {\n  deleteBlog(blogId: $blogId) {\n    data {\n      _id\n    }\n    success\n    message\n  }\n}\n\nmutation UpdateBlog($blogId: ID!, $blogData: BlogInput!) {\n  updateBlog(blogId: $blogId, blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nmutation CreateBlog($blogData: BlogInput!) {\n  createBlog(blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nquery GetBlogStats {\n  getBlogStats {\n    success\n    message\n    data {\n      draftPosts\n      totalPosts\n      publishedPosts\n      totalViews\n      tags {\n        count\n        tag\n      }\n    }\n  }\n}": typeof types.BlogPublicFragmentFragmentDoc;
};
const documents: Documents = {
  "fragment BlogPublicFragment on BlogPublic {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n}\n\nfragment BlogFragment on Blog {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n  content\n}\n\nquery GetBlogs($page: Int, $limit: Int, $filter: BlogFilter) {\n  getBlogs(page: $page, limit: $limit, filter: $filter) {\n    success\n    message\n    data {\n      docs {\n        ...BlogPublicFragment\n      }\n      totalDocs\n      limit\n      totalPages\n      page\n      pagingCounter\n      hasPrevPage\n      hasNextPage\n      prevPage\n      nextPage\n    }\n  }\n}\n\nquery GetBlog($slug: String!) {\n  getBlog(slug: $slug) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nquery GetBlogById($id: ID!) {\n  getBlogById(id: $id) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nmutation DeleteBlog($blogId: ID!) {\n  deleteBlog(blogId: $blogId) {\n    data {\n      _id\n    }\n    success\n    message\n  }\n}\n\nmutation UpdateBlog($blogId: ID!, $blogData: BlogInput!) {\n  updateBlog(blogId: $blogId, blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nmutation CreateBlog($blogData: BlogInput!) {\n  createBlog(blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nquery GetBlogStats {\n  getBlogStats {\n    success\n    message\n    data {\n      draftPosts\n      totalPosts\n      publishedPosts\n      totalViews\n      tags {\n        count\n        tag\n      }\n    }\n  }\n}":
    types.BlogPublicFragmentFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "fragment BlogPublicFragment on BlogPublic {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n}\n\nfragment BlogFragment on Blog {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n  content\n}\n\nquery GetBlogs($page: Int, $limit: Int, $filter: BlogFilter) {\n  getBlogs(page: $page, limit: $limit, filter: $filter) {\n    success\n    message\n    data {\n      docs {\n        ...BlogPublicFragment\n      }\n      totalDocs\n      limit\n      totalPages\n      page\n      pagingCounter\n      hasPrevPage\n      hasNextPage\n      prevPage\n      nextPage\n    }\n  }\n}\n\nquery GetBlog($slug: String!) {\n  getBlog(slug: $slug) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nquery GetBlogById($id: ID!) {\n  getBlogById(id: $id) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nmutation DeleteBlog($blogId: ID!) {\n  deleteBlog(blogId: $blogId) {\n    data {\n      _id\n    }\n    success\n    message\n  }\n}\n\nmutation UpdateBlog($blogId: ID!, $blogData: BlogInput!) {\n  updateBlog(blogId: $blogId, blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nmutation CreateBlog($blogData: BlogInput!) {\n  createBlog(blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nquery GetBlogStats {\n  getBlogStats {\n    success\n    message\n    data {\n      draftPosts\n      totalPosts\n      publishedPosts\n      totalViews\n      tags {\n        count\n        tag\n      }\n    }\n  }\n}",
): (typeof documents)["fragment BlogPublicFragment on BlogPublic {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n}\n\nfragment BlogFragment on Blog {\n  _id\n  title\n  summary\n  status\n  createdAt\n  updatedAt\n  timesViewed\n  slug\n  mainImage\n  tags\n  seo_title\n  seo_desc\n  content\n}\n\nquery GetBlogs($page: Int, $limit: Int, $filter: BlogFilter) {\n  getBlogs(page: $page, limit: $limit, filter: $filter) {\n    success\n    message\n    data {\n      docs {\n        ...BlogPublicFragment\n      }\n      totalDocs\n      limit\n      totalPages\n      page\n      pagingCounter\n      hasPrevPage\n      hasNextPage\n      prevPage\n      nextPage\n    }\n  }\n}\n\nquery GetBlog($slug: String!) {\n  getBlog(slug: $slug) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nquery GetBlogById($id: ID!) {\n  getBlogById(id: $id) {\n    success\n    message\n    data {\n      ...BlogFragment\n    }\n  }\n}\n\nmutation DeleteBlog($blogId: ID!) {\n  deleteBlog(blogId: $blogId) {\n    data {\n      _id\n    }\n    success\n    message\n  }\n}\n\nmutation UpdateBlog($blogId: ID!, $blogData: BlogInput!) {\n  updateBlog(blogId: $blogId, blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nmutation CreateBlog($blogData: BlogInput!) {\n  createBlog(blogData: $blogData) {\n    success\n    message\n    data {\n      _id\n      title\n      summary\n      content\n      status\n      slug\n      mainImage\n      tags\n      seo_title\n      seo_desc\n      author {\n        _id\n        displayName\n      }\n      timesViewed\n      savedCount\n      publicationScore\n      score\n      ogImage\n      createdAt\n      updatedAt\n    }\n  }\n}\n\nquery GetBlogStats {\n  getBlogStats {\n    success\n    message\n    data {\n      draftPosts\n      totalPosts\n      publishedPosts\n      totalViews\n      tags {\n        count\n        tag\n      }\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
